### ISSUE TITLE
New version of rply now depends on appdir

### ISSUE THREAD

**Issue by ltratt** [hippyvm/hippyvm#108]
In the pypy-bridge branch, I think `requirements.txt` needs to be updated to also include https://pypi.python.org/pypi/appdirs/1.4.0#downloads, which `rply` now seems to need.

**Comment by vext01** [comment]
Hey Laurie,

We shouldn't need to list appdirs as the tools which consume a `requirements.txt` will automatically deal with dependencies:

```
$ echo "rply" > requirements.txt
$ pip install -r requirements.txt
Collecting rply (from -r requirements.txt (line 1))
  Using cached rply-0.7.4-py2.py3-none-any.whl
Collecting appdirs (from rply->-r requirements.txt (line 1))
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Installing collected packages: appdirs, rply
Successfully installed appdirs-1.4.0 rply-0.7.4
```

Did you have a use case where appdirs was not being installed automatically?

**Comment by ltratt** [comment]
Yes -- when someone (e.g. me) doesn't trust things like Pip and installs things by hand ;) `requirements.txt` is kind of useful then.

I wonder if we should fix the versions that we mandate? e.g. rply's interface may change incompatibly in the future.

**Comment by vext01** [comment]
Hrm, as i recall, even if you run `setup.py` manually the dependencies should be managed. Can you describe how you install stuff.

As for fixing versions, pip has a mode for generating `requirements.txt` with fixed versions (this is actually how you are supposed to make requirements files, but I've admittedly never tried it). I agree that it might not be a good for keeping things working in the future.

**Comment by ltratt** [comment]
There isn't a `setup.py`?

**Comment by vext01** [comment]
In rply, I mean: https://github.com/alex/rply/blob/master/setup.py

**Comment by ltratt** [comment]
Personally, I just download it into the current directory... I don't want to actually install it (nor do I want to run an arbitrary `setup.py` if I can avoid it).

Let me put it another way: is there any disadvantage in putting `appdirs` into `requirements.txt`?

**Comment by vext01** [comment]
We can add it, but I can't guarantee you haven't missed other dependencies.

You're bypassing the standard tools, so you are kinda on your own with dependency management at that stage :\

**Comment by ltratt** [comment]
It works fine with `rply` and `appdirs`.

**Comment by vext01** [comment]
I've made a pull request.

You should consider making friends with pip and virtualenv. It's easy to make throwaway Python environments that don't interfere with the system or user Python environments, and dependency management is automatic. Imagine installing something like jupyter (which has some 20+ deps) by hand, you would go nuts :P

**Comment by ltratt** [comment]
Life is short and there are too many package managers for my poor little brain ;)

Anyway, thanks for fixing this. I'm closing this issue now.
