### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by josegonzalez** [hippyvm/hippyvm#113]
http://hippyvm.com doesn't resolve for me :(

**Comment by vext01** [comment]
On Sun, Mar 13, 2016 at 08:29:57PM -0700, Jose Diaz-Gonzalez wrote:

> http://hippyvm.com doesn't resolve for me :(

My guess. Since HippyVM is not being actively developed, the developers
stopped hosting the web-site.

Cheers

## 

Best Regards
Edd Barrett

http://www.theunixzoo.co.uk

**Comment by xando** [comment]
Hey,

Everything what Edd said. Also we moved the website with the note to
http://hippyvm.baroquesoftware.com/

Edd, let me know if this works for you as well?

**Comment by josegonzalez** [comment]
Nbd, closing the issue then. Just something I noticed while fixing links on the awesome-php list.

**Comment by josegonzalez** [comment]
Note: may be worth updating the url on the repo description.
